# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-06 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_marketingpreference_mailchimp_subscribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingpreference',
            name='mailchimp_subscribed',
        ),
    ]
